template: testify
formatter: goimports

template-data:
  unroll-variadic: true

dir: "{{.InterfaceDir}}"
pkgname: "{{.SrcPackageName}}"
structname: "Mock{{.InterfaceName}}"

packages:
  github.com/roessland/withoutings/pkg/withoutings/domain/account:
    interfaces:
      Repo:
        config:
          filename: "accountrepo_mock.go"

  github.com/roessland/withoutings/pkg/withoutings/domain/subscription:
    interfaces:
      Repo:
        config:
          filename: "subscriptionrepo_mock.go"

  github.com/roessland/withoutings/pkg/withoutings/domain/withings:
    interfaces:
      Repo:
        config:
          filename: "domain_withingsrepo_mock.go"

  github.com/roessland/withoutings/pkg/withoutings/app/service/withings:
    interfaces:
      Service:
        config:
          filename: "withings_service_mock.go"
