// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgtype"
)

type Account struct {
	AccountID                 int64
	WithingsUserID            string
	WithingsAccessToken       string
	WithingsRefreshToken      string
	WithingsAccessTokenExpiry time.Time
	WithingsScopes            string
}

type Session struct {
	SessionID uuid.UUID
	Data      pgtype.JSONB
	Created   time.Time
	Expiry    time.Time
}

type Subscription struct {
	SubscriptionID int32
	AccountID      sql.NullInt64
	Appli          int32
	Callbackurl    string
	Comment        string
}
