// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package withings

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRepo creates a new instance of MockRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepo {
	mock := &MockRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepo is an autogenerated mock type for the Repo type
type MockRepo struct {
	mock.Mock
}

type MockRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepo) EXPECT() *MockRepo_Expecter {
	return &MockRepo_Expecter{mock: &_m.Mock}
}

// AuthCodeURL provides a mock function for the type MockRepo
func (_mock *MockRepo) AuthCodeURL(nonce string) string {
	ret := _mock.Called(nonce)

	if len(ret) == 0 {
		panic("no return value specified for AuthCodeURL")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(nonce)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockRepo_AuthCodeURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthCodeURL'
type MockRepo_AuthCodeURL_Call struct {
	*mock.Call
}

// AuthCodeURL is a helper method to define mock.On call
//   - nonce string
func (_e *MockRepo_Expecter) AuthCodeURL(nonce interface{}) *MockRepo_AuthCodeURL_Call {
	return &MockRepo_AuthCodeURL_Call{Call: _e.mock.On("AuthCodeURL", nonce)}
}

func (_c *MockRepo_AuthCodeURL_Call) Run(run func(nonce string)) *MockRepo_AuthCodeURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepo_AuthCodeURL_Call) Return(s string) *MockRepo_AuthCodeURL_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockRepo_AuthCodeURL_Call) RunAndReturn(run func(nonce string) string) *MockRepo_AuthCodeURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccessToken provides a mock function for the type MockRepo
func (_mock *MockRepo) GetAccessToken(ctx context.Context, authCode string) (*Token, error) {
	ret := _mock.Called(ctx, authCode)

	if len(ret) == 0 {
		panic("no return value specified for GetAccessToken")
	}

	var r0 *Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*Token, error)); ok {
		return returnFunc(ctx, authCode)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *Token); ok {
		r0 = returnFunc(ctx, authCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, authCode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepo_GetAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccessToken'
type MockRepo_GetAccessToken_Call struct {
	*mock.Call
}

// GetAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - authCode string
func (_e *MockRepo_Expecter) GetAccessToken(ctx interface{}, authCode interface{}) *MockRepo_GetAccessToken_Call {
	return &MockRepo_GetAccessToken_Call{Call: _e.mock.On("GetAccessToken", ctx, authCode)}
}

func (_c *MockRepo_GetAccessToken_Call) Run(run func(ctx context.Context, authCode string)) *MockRepo_GetAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepo_GetAccessToken_Call) Return(token *Token, err error) *MockRepo_GetAccessToken_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockRepo_GetAccessToken_Call) RunAndReturn(run func(ctx context.Context, authCode string) (*Token, error)) *MockRepo_GetAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// MeasureGetactivity provides a mock function for the type MockRepo
func (_mock *MockRepo) MeasureGetactivity(ctx context.Context, accessToken string, params MeasureGetactivityParams) (*MeasureGetactivityResponse, error) {
	ret := _mock.Called(ctx, accessToken, params)

	if len(ret) == 0 {
		panic("no return value specified for MeasureGetactivity")
	}

	var r0 *MeasureGetactivityResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, MeasureGetactivityParams) (*MeasureGetactivityResponse, error)); ok {
		return returnFunc(ctx, accessToken, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, MeasureGetactivityParams) *MeasureGetactivityResponse); ok {
		r0 = returnFunc(ctx, accessToken, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*MeasureGetactivityResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, MeasureGetactivityParams) error); ok {
		r1 = returnFunc(ctx, accessToken, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepo_MeasureGetactivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MeasureGetactivity'
type MockRepo_MeasureGetactivity_Call struct {
	*mock.Call
}

// MeasureGetactivity is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
//   - params MeasureGetactivityParams
func (_e *MockRepo_Expecter) MeasureGetactivity(ctx interface{}, accessToken interface{}, params interface{}) *MockRepo_MeasureGetactivity_Call {
	return &MockRepo_MeasureGetactivity_Call{Call: _e.mock.On("MeasureGetactivity", ctx, accessToken, params)}
}

func (_c *MockRepo_MeasureGetactivity_Call) Run(run func(ctx context.Context, accessToken string, params MeasureGetactivityParams)) *MockRepo_MeasureGetactivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 MeasureGetactivityParams
		if args[2] != nil {
			arg2 = args[2].(MeasureGetactivityParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepo_MeasureGetactivity_Call) Return(measureGetactivityResponse *MeasureGetactivityResponse, err error) *MockRepo_MeasureGetactivity_Call {
	_c.Call.Return(measureGetactivityResponse, err)
	return _c
}

func (_c *MockRepo_MeasureGetactivity_Call) RunAndReturn(run func(ctx context.Context, accessToken string, params MeasureGetactivityParams) (*MeasureGetactivityResponse, error)) *MockRepo_MeasureGetactivity_Call {
	_c.Call.Return(run)
	return _c
}

// MeasureGetintradayactivity provides a mock function for the type MockRepo
func (_mock *MockRepo) MeasureGetintradayactivity(ctx context.Context, accessToken string, params MeasureGetintradayactivityParams) (*MeasureGetintradayactivityResponse, error) {
	ret := _mock.Called(ctx, accessToken, params)

	if len(ret) == 0 {
		panic("no return value specified for MeasureGetintradayactivity")
	}

	var r0 *MeasureGetintradayactivityResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, MeasureGetintradayactivityParams) (*MeasureGetintradayactivityResponse, error)); ok {
		return returnFunc(ctx, accessToken, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, MeasureGetintradayactivityParams) *MeasureGetintradayactivityResponse); ok {
		r0 = returnFunc(ctx, accessToken, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*MeasureGetintradayactivityResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, MeasureGetintradayactivityParams) error); ok {
		r1 = returnFunc(ctx, accessToken, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepo_MeasureGetintradayactivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MeasureGetintradayactivity'
type MockRepo_MeasureGetintradayactivity_Call struct {
	*mock.Call
}

// MeasureGetintradayactivity is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
//   - params MeasureGetintradayactivityParams
func (_e *MockRepo_Expecter) MeasureGetintradayactivity(ctx interface{}, accessToken interface{}, params interface{}) *MockRepo_MeasureGetintradayactivity_Call {
	return &MockRepo_MeasureGetintradayactivity_Call{Call: _e.mock.On("MeasureGetintradayactivity", ctx, accessToken, params)}
}

func (_c *MockRepo_MeasureGetintradayactivity_Call) Run(run func(ctx context.Context, accessToken string, params MeasureGetintradayactivityParams)) *MockRepo_MeasureGetintradayactivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 MeasureGetintradayactivityParams
		if args[2] != nil {
			arg2 = args[2].(MeasureGetintradayactivityParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepo_MeasureGetintradayactivity_Call) Return(measureGetintradayactivityResponse *MeasureGetintradayactivityResponse, err error) *MockRepo_MeasureGetintradayactivity_Call {
	_c.Call.Return(measureGetintradayactivityResponse, err)
	return _c
}

func (_c *MockRepo_MeasureGetintradayactivity_Call) RunAndReturn(run func(ctx context.Context, accessToken string, params MeasureGetintradayactivityParams) (*MeasureGetintradayactivityResponse, error)) *MockRepo_MeasureGetintradayactivity_Call {
	_c.Call.Return(run)
	return _c
}

// MeasureGetmeas provides a mock function for the type MockRepo
func (_mock *MockRepo) MeasureGetmeas(ctx context.Context, accessToken string, params MeasureGetmeasParams) (*MeasureGetmeasResponse, error) {
	ret := _mock.Called(ctx, accessToken, params)

	if len(ret) == 0 {
		panic("no return value specified for MeasureGetmeas")
	}

	var r0 *MeasureGetmeasResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, MeasureGetmeasParams) (*MeasureGetmeasResponse, error)); ok {
		return returnFunc(ctx, accessToken, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, MeasureGetmeasParams) *MeasureGetmeasResponse); ok {
		r0 = returnFunc(ctx, accessToken, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*MeasureGetmeasResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, MeasureGetmeasParams) error); ok {
		r1 = returnFunc(ctx, accessToken, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepo_MeasureGetmeas_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MeasureGetmeas'
type MockRepo_MeasureGetmeas_Call struct {
	*mock.Call
}

// MeasureGetmeas is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
//   - params MeasureGetmeasParams
func (_e *MockRepo_Expecter) MeasureGetmeas(ctx interface{}, accessToken interface{}, params interface{}) *MockRepo_MeasureGetmeas_Call {
	return &MockRepo_MeasureGetmeas_Call{Call: _e.mock.On("MeasureGetmeas", ctx, accessToken, params)}
}

func (_c *MockRepo_MeasureGetmeas_Call) Run(run func(ctx context.Context, accessToken string, params MeasureGetmeasParams)) *MockRepo_MeasureGetmeas_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 MeasureGetmeasParams
		if args[2] != nil {
			arg2 = args[2].(MeasureGetmeasParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepo_MeasureGetmeas_Call) Return(measureGetmeasResponse *MeasureGetmeasResponse, err error) *MockRepo_MeasureGetmeas_Call {
	_c.Call.Return(measureGetmeasResponse, err)
	return _c
}

func (_c *MockRepo_MeasureGetmeas_Call) RunAndReturn(run func(ctx context.Context, accessToken string, params MeasureGetmeasParams) (*MeasureGetmeasResponse, error)) *MockRepo_MeasureGetmeas_Call {
	_c.Call.Return(run)
	return _c
}

// MeasureGetworkouts provides a mock function for the type MockRepo
func (_mock *MockRepo) MeasureGetworkouts(ctx context.Context, accessToken string, params MeasureGetworkoutsParams) (*MeasureGetworkoutsResponse, error) {
	ret := _mock.Called(ctx, accessToken, params)

	if len(ret) == 0 {
		panic("no return value specified for MeasureGetworkouts")
	}

	var r0 *MeasureGetworkoutsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, MeasureGetworkoutsParams) (*MeasureGetworkoutsResponse, error)); ok {
		return returnFunc(ctx, accessToken, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, MeasureGetworkoutsParams) *MeasureGetworkoutsResponse); ok {
		r0 = returnFunc(ctx, accessToken, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*MeasureGetworkoutsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, MeasureGetworkoutsParams) error); ok {
		r1 = returnFunc(ctx, accessToken, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepo_MeasureGetworkouts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MeasureGetworkouts'
type MockRepo_MeasureGetworkouts_Call struct {
	*mock.Call
}

// MeasureGetworkouts is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
//   - params MeasureGetworkoutsParams
func (_e *MockRepo_Expecter) MeasureGetworkouts(ctx interface{}, accessToken interface{}, params interface{}) *MockRepo_MeasureGetworkouts_Call {
	return &MockRepo_MeasureGetworkouts_Call{Call: _e.mock.On("MeasureGetworkouts", ctx, accessToken, params)}
}

func (_c *MockRepo_MeasureGetworkouts_Call) Run(run func(ctx context.Context, accessToken string, params MeasureGetworkoutsParams)) *MockRepo_MeasureGetworkouts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 MeasureGetworkoutsParams
		if args[2] != nil {
			arg2 = args[2].(MeasureGetworkoutsParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepo_MeasureGetworkouts_Call) Return(measureGetworkoutsResponse *MeasureGetworkoutsResponse, err error) *MockRepo_MeasureGetworkouts_Call {
	_c.Call.Return(measureGetworkoutsResponse, err)
	return _c
}

func (_c *MockRepo_MeasureGetworkouts_Call) RunAndReturn(run func(ctx context.Context, accessToken string, params MeasureGetworkoutsParams) (*MeasureGetworkoutsResponse, error)) *MockRepo_MeasureGetworkouts_Call {
	_c.Call.Return(run)
	return _c
}

// NotifyList provides a mock function for the type MockRepo
func (_mock *MockRepo) NotifyList(ctx context.Context, accessToken string, params NotifyListParams) (*NotifyListResponse, error) {
	ret := _mock.Called(ctx, accessToken, params)

	if len(ret) == 0 {
		panic("no return value specified for NotifyList")
	}

	var r0 *NotifyListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, NotifyListParams) (*NotifyListResponse, error)); ok {
		return returnFunc(ctx, accessToken, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, NotifyListParams) *NotifyListResponse); ok {
		r0 = returnFunc(ctx, accessToken, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*NotifyListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, NotifyListParams) error); ok {
		r1 = returnFunc(ctx, accessToken, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepo_NotifyList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyList'
type MockRepo_NotifyList_Call struct {
	*mock.Call
}

// NotifyList is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
//   - params NotifyListParams
func (_e *MockRepo_Expecter) NotifyList(ctx interface{}, accessToken interface{}, params interface{}) *MockRepo_NotifyList_Call {
	return &MockRepo_NotifyList_Call{Call: _e.mock.On("NotifyList", ctx, accessToken, params)}
}

func (_c *MockRepo_NotifyList_Call) Run(run func(ctx context.Context, accessToken string, params NotifyListParams)) *MockRepo_NotifyList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 NotifyListParams
		if args[2] != nil {
			arg2 = args[2].(NotifyListParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepo_NotifyList_Call) Return(notifyListResponse *NotifyListResponse, err error) *MockRepo_NotifyList_Call {
	_c.Call.Return(notifyListResponse, err)
	return _c
}

func (_c *MockRepo_NotifyList_Call) RunAndReturn(run func(ctx context.Context, accessToken string, params NotifyListParams) (*NotifyListResponse, error)) *MockRepo_NotifyList_Call {
	_c.Call.Return(run)
	return _c
}

// NotifySubscribe provides a mock function for the type MockRepo
func (_mock *MockRepo) NotifySubscribe(ctx context.Context, accessToken string, params NotifySubscribeParams) (*NotifySubscribeResponse, error) {
	ret := _mock.Called(ctx, accessToken, params)

	if len(ret) == 0 {
		panic("no return value specified for NotifySubscribe")
	}

	var r0 *NotifySubscribeResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, NotifySubscribeParams) (*NotifySubscribeResponse, error)); ok {
		return returnFunc(ctx, accessToken, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, NotifySubscribeParams) *NotifySubscribeResponse); ok {
		r0 = returnFunc(ctx, accessToken, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*NotifySubscribeResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, NotifySubscribeParams) error); ok {
		r1 = returnFunc(ctx, accessToken, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepo_NotifySubscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifySubscribe'
type MockRepo_NotifySubscribe_Call struct {
	*mock.Call
}

// NotifySubscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
//   - params NotifySubscribeParams
func (_e *MockRepo_Expecter) NotifySubscribe(ctx interface{}, accessToken interface{}, params interface{}) *MockRepo_NotifySubscribe_Call {
	return &MockRepo_NotifySubscribe_Call{Call: _e.mock.On("NotifySubscribe", ctx, accessToken, params)}
}

func (_c *MockRepo_NotifySubscribe_Call) Run(run func(ctx context.Context, accessToken string, params NotifySubscribeParams)) *MockRepo_NotifySubscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 NotifySubscribeParams
		if args[2] != nil {
			arg2 = args[2].(NotifySubscribeParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepo_NotifySubscribe_Call) Return(notifySubscribeResponse *NotifySubscribeResponse, err error) *MockRepo_NotifySubscribe_Call {
	_c.Call.Return(notifySubscribeResponse, err)
	return _c
}

func (_c *MockRepo_NotifySubscribe_Call) RunAndReturn(run func(ctx context.Context, accessToken string, params NotifySubscribeParams) (*NotifySubscribeResponse, error)) *MockRepo_NotifySubscribe_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshAccessToken provides a mock function for the type MockRepo
func (_mock *MockRepo) RefreshAccessToken(ctx context.Context, refreshToken string) (*Token, error) {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshAccessToken")
	}

	var r0 *Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*Token, error)); ok {
		return returnFunc(ctx, refreshToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *Token); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepo_RefreshAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshAccessToken'
type MockRepo_RefreshAccessToken_Call struct {
	*mock.Call
}

// RefreshAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockRepo_Expecter) RefreshAccessToken(ctx interface{}, refreshToken interface{}) *MockRepo_RefreshAccessToken_Call {
	return &MockRepo_RefreshAccessToken_Call{Call: _e.mock.On("RefreshAccessToken", ctx, refreshToken)}
}

func (_c *MockRepo_RefreshAccessToken_Call) Run(run func(ctx context.Context, refreshToken string)) *MockRepo_RefreshAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepo_RefreshAccessToken_Call) Return(token *Token, err error) *MockRepo_RefreshAccessToken_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockRepo_RefreshAccessToken_Call) RunAndReturn(run func(ctx context.Context, refreshToken string) (*Token, error)) *MockRepo_RefreshAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// SleepGet provides a mock function for the type MockRepo
func (_mock *MockRepo) SleepGet(ctx context.Context, accessToken string, params SleepGetParams) (*SleepGetResponse, error) {
	ret := _mock.Called(ctx, accessToken, params)

	if len(ret) == 0 {
		panic("no return value specified for SleepGet")
	}

	var r0 *SleepGetResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, SleepGetParams) (*SleepGetResponse, error)); ok {
		return returnFunc(ctx, accessToken, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, SleepGetParams) *SleepGetResponse); ok {
		r0 = returnFunc(ctx, accessToken, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*SleepGetResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, SleepGetParams) error); ok {
		r1 = returnFunc(ctx, accessToken, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepo_SleepGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SleepGet'
type MockRepo_SleepGet_Call struct {
	*mock.Call
}

// SleepGet is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
//   - params SleepGetParams
func (_e *MockRepo_Expecter) SleepGet(ctx interface{}, accessToken interface{}, params interface{}) *MockRepo_SleepGet_Call {
	return &MockRepo_SleepGet_Call{Call: _e.mock.On("SleepGet", ctx, accessToken, params)}
}

func (_c *MockRepo_SleepGet_Call) Run(run func(ctx context.Context, accessToken string, params SleepGetParams)) *MockRepo_SleepGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 SleepGetParams
		if args[2] != nil {
			arg2 = args[2].(SleepGetParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepo_SleepGet_Call) Return(sleepGetResponse *SleepGetResponse, err error) *MockRepo_SleepGet_Call {
	_c.Call.Return(sleepGetResponse, err)
	return _c
}

func (_c *MockRepo_SleepGet_Call) RunAndReturn(run func(ctx context.Context, accessToken string, params SleepGetParams) (*SleepGetResponse, error)) *MockRepo_SleepGet_Call {
	_c.Call.Return(run)
	return _c
}

// SleepGetsummary provides a mock function for the type MockRepo
func (_mock *MockRepo) SleepGetsummary(ctx context.Context, accessToken string, params SleepGetsummaryParams) (*SleepGetsummaryResponse, error) {
	ret := _mock.Called(ctx, accessToken, params)

	if len(ret) == 0 {
		panic("no return value specified for SleepGetsummary")
	}

	var r0 *SleepGetsummaryResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, SleepGetsummaryParams) (*SleepGetsummaryResponse, error)); ok {
		return returnFunc(ctx, accessToken, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, SleepGetsummaryParams) *SleepGetsummaryResponse); ok {
		r0 = returnFunc(ctx, accessToken, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*SleepGetsummaryResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, SleepGetsummaryParams) error); ok {
		r1 = returnFunc(ctx, accessToken, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepo_SleepGetsummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SleepGetsummary'
type MockRepo_SleepGetsummary_Call struct {
	*mock.Call
}

// SleepGetsummary is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
//   - params SleepGetsummaryParams
func (_e *MockRepo_Expecter) SleepGetsummary(ctx interface{}, accessToken interface{}, params interface{}) *MockRepo_SleepGetsummary_Call {
	return &MockRepo_SleepGetsummary_Call{Call: _e.mock.On("SleepGetsummary", ctx, accessToken, params)}
}

func (_c *MockRepo_SleepGetsummary_Call) Run(run func(ctx context.Context, accessToken string, params SleepGetsummaryParams)) *MockRepo_SleepGetsummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 SleepGetsummaryParams
		if args[2] != nil {
			arg2 = args[2].(SleepGetsummaryParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepo_SleepGetsummary_Call) Return(sleepGetsummaryResponse *SleepGetsummaryResponse, err error) *MockRepo_SleepGetsummary_Call {
	_c.Call.Return(sleepGetsummaryResponse, err)
	return _c
}

func (_c *MockRepo_SleepGetsummary_Call) RunAndReturn(run func(ctx context.Context, accessToken string, params SleepGetsummaryParams) (*SleepGetsummaryResponse, error)) *MockRepo_SleepGetsummary_Call {
	_c.Call.Return(run)
	return _c
}
