package withings

import (
	"context"
)

// Mock generated by `make generate-mocks` (mockery v3, configured via
// .mockery.yaml at the repo root).
type Repo interface {
	AuthCodeURL(nonce string) string
	GetAccessToken(ctx context.Context, authCode string) (*Token, error)
	RefreshAccessToken(ctx context.Context, refreshToken string) (*Token, error)
	NotifySubscribe(ctx context.Context, accessToken string, params NotifySubscribeParams) (*NotifySubscribeResponse, error)
	NotifyList(ctx context.Context, accessToken string, params NotifyListParams) (*NotifyListResponse, error)
	SleepGetsummary(ctx context.Context, accessToken string, params SleepGetsummaryParams) (*SleepGetsummaryResponse, error)
	SleepGet(ctx context.Context, accessToken string, params SleepGetParams) (*SleepGetResponse, error)
	MeasureGetmeas(ctx context.Context, accessToken string, params MeasureGetmeasParams) (*MeasureGetmeasResponse, error)
}
