// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: account.sql

package db

import (
	"context"
	"time"
)

const createAccount = `-- name: CreateAccount :exec
INSERT INTO account (withings_user_id, withings_access_token, withings_refresh_token,
                         withings_access_token_expiry, withings_scopes)
VALUES ($1, $2, $3, $4, $5)
`

type CreateAccountParams struct {
	WithingsUserID            string
	WithingsAccessToken       string
	WithingsRefreshToken      string
	WithingsAccessTokenExpiry time.Time
	WithingsScopes            string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.Exec(ctx, createAccount,
		arg.WithingsUserID,
		arg.WithingsAccessToken,
		arg.WithingsRefreshToken,
		arg.WithingsAccessTokenExpiry,
		arg.WithingsScopes,
	)
	return err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE
FROM account
WHERE account_id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, accountID int64) error {
	_, err := q.db.Exec(ctx, deleteAccount, accountID)
	return err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT account_id, withings_user_id, withings_access_token, withings_refresh_token, withings_access_token_expiry, withings_scopes
FROM account
WHERE account_id = $1
LIMIT 1
`

func (q *Queries) GetAccountByID(ctx context.Context, accountID int64) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, accountID)
	var i Account
	err := row.Scan(
		&i.AccountID,
		&i.WithingsUserID,
		&i.WithingsAccessToken,
		&i.WithingsRefreshToken,
		&i.WithingsAccessTokenExpiry,
		&i.WithingsScopes,
	)
	return i, err
}

const getAccountByWithingsUserID = `-- name: GetAccountByWithingsUserID :one
SELECT account_id, withings_user_id, withings_access_token, withings_refresh_token, withings_access_token_expiry, withings_scopes
FROM account
WHERE withings_user_id = $1
LIMIT 1
`

func (q *Queries) GetAccountByWithingsUserID(ctx context.Context, withingsUserID string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByWithingsUserID, withingsUserID)
	var i Account
	err := row.Scan(
		&i.AccountID,
		&i.WithingsUserID,
		&i.WithingsAccessToken,
		&i.WithingsRefreshToken,
		&i.WithingsAccessTokenExpiry,
		&i.WithingsScopes,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT account_id, withings_user_id, withings_access_token, withings_refresh_token, withings_access_token_expiry, withings_scopes
FROM account
ORDER BY account_id
`

func (q *Queries) ListAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.AccountID,
			&i.WithingsUserID,
			&i.WithingsAccessToken,
			&i.WithingsRefreshToken,
			&i.WithingsAccessTokenExpiry,
			&i.WithingsScopes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
