// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package withings

import (
	"context"

	"github.com/roessland/withoutings/pkg/withoutings/domain/account"
	"github.com/roessland/withoutings/pkg/withoutings/domain/withings"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// MeasureGetmeas provides a mock function for the type MockService
func (_mock *MockService) MeasureGetmeas(ctx context.Context, acc *account.Account, params withings.MeasureGetmeasParams) (*withings.MeasureGetmeasResponse, error) {
	ret := _mock.Called(ctx, acc, params)

	if len(ret) == 0 {
		panic("no return value specified for MeasureGetmeas")
	}

	var r0 *withings.MeasureGetmeasResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *account.Account, withings.MeasureGetmeasParams) (*withings.MeasureGetmeasResponse, error)); ok {
		return returnFunc(ctx, acc, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *account.Account, withings.MeasureGetmeasParams) *withings.MeasureGetmeasResponse); ok {
		r0 = returnFunc(ctx, acc, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*withings.MeasureGetmeasResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *account.Account, withings.MeasureGetmeasParams) error); ok {
		r1 = returnFunc(ctx, acc, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_MeasureGetmeas_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MeasureGetmeas'
type MockService_MeasureGetmeas_Call struct {
	*mock.Call
}

// MeasureGetmeas is a helper method to define mock.On call
//   - ctx context.Context
//   - acc *account.Account
//   - params withings.MeasureGetmeasParams
func (_e *MockService_Expecter) MeasureGetmeas(ctx interface{}, acc interface{}, params interface{}) *MockService_MeasureGetmeas_Call {
	return &MockService_MeasureGetmeas_Call{Call: _e.mock.On("MeasureGetmeas", ctx, acc, params)}
}

func (_c *MockService_MeasureGetmeas_Call) Run(run func(ctx context.Context, acc *account.Account, params withings.MeasureGetmeasParams)) *MockService_MeasureGetmeas_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *account.Account
		if args[1] != nil {
			arg1 = args[1].(*account.Account)
		}
		var arg2 withings.MeasureGetmeasParams
		if args[2] != nil {
			arg2 = args[2].(withings.MeasureGetmeasParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_MeasureGetmeas_Call) Return(measureGetmeasResponse *withings.MeasureGetmeasResponse, err error) *MockService_MeasureGetmeas_Call {
	_c.Call.Return(measureGetmeasResponse, err)
	return _c
}

func (_c *MockService_MeasureGetmeas_Call) RunAndReturn(run func(ctx context.Context, acc *account.Account, params withings.MeasureGetmeasParams) (*withings.MeasureGetmeasResponse, error)) *MockService_MeasureGetmeas_Call {
	_c.Call.Return(run)
	return _c
}

// NotifyList provides a mock function for the type MockService
func (_mock *MockService) NotifyList(ctx context.Context, acc *account.Account, params withings.NotifyListParams) (*withings.NotifyListResponse, error) {
	ret := _mock.Called(ctx, acc, params)

	if len(ret) == 0 {
		panic("no return value specified for NotifyList")
	}

	var r0 *withings.NotifyListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *account.Account, withings.NotifyListParams) (*withings.NotifyListResponse, error)); ok {
		return returnFunc(ctx, acc, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *account.Account, withings.NotifyListParams) *withings.NotifyListResponse); ok {
		r0 = returnFunc(ctx, acc, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*withings.NotifyListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *account.Account, withings.NotifyListParams) error); ok {
		r1 = returnFunc(ctx, acc, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_NotifyList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyList'
type MockService_NotifyList_Call struct {
	*mock.Call
}

// NotifyList is a helper method to define mock.On call
//   - ctx context.Context
//   - acc *account.Account
//   - params withings.NotifyListParams
func (_e *MockService_Expecter) NotifyList(ctx interface{}, acc interface{}, params interface{}) *MockService_NotifyList_Call {
	return &MockService_NotifyList_Call{Call: _e.mock.On("NotifyList", ctx, acc, params)}
}

func (_c *MockService_NotifyList_Call) Run(run func(ctx context.Context, acc *account.Account, params withings.NotifyListParams)) *MockService_NotifyList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *account.Account
		if args[1] != nil {
			arg1 = args[1].(*account.Account)
		}
		var arg2 withings.NotifyListParams
		if args[2] != nil {
			arg2 = args[2].(withings.NotifyListParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_NotifyList_Call) Return(notifyListResponse *withings.NotifyListResponse, err error) *MockService_NotifyList_Call {
	_c.Call.Return(notifyListResponse, err)
	return _c
}

func (_c *MockService_NotifyList_Call) RunAndReturn(run func(ctx context.Context, acc *account.Account, params withings.NotifyListParams) (*withings.NotifyListResponse, error)) *MockService_NotifyList_Call {
	_c.Call.Return(run)
	return _c
}

// NotifySubscribe provides a mock function for the type MockService
func (_mock *MockService) NotifySubscribe(ctx context.Context, acc *account.Account, params withings.NotifySubscribeParams) (*withings.NotifySubscribeResponse, error) {
	ret := _mock.Called(ctx, acc, params)

	if len(ret) == 0 {
		panic("no return value specified for NotifySubscribe")
	}

	var r0 *withings.NotifySubscribeResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *account.Account, withings.NotifySubscribeParams) (*withings.NotifySubscribeResponse, error)); ok {
		return returnFunc(ctx, acc, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *account.Account, withings.NotifySubscribeParams) *withings.NotifySubscribeResponse); ok {
		r0 = returnFunc(ctx, acc, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*withings.NotifySubscribeResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *account.Account, withings.NotifySubscribeParams) error); ok {
		r1 = returnFunc(ctx, acc, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_NotifySubscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifySubscribe'
type MockService_NotifySubscribe_Call struct {
	*mock.Call
}

// NotifySubscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - acc *account.Account
//   - params withings.NotifySubscribeParams
func (_e *MockService_Expecter) NotifySubscribe(ctx interface{}, acc interface{}, params interface{}) *MockService_NotifySubscribe_Call {
	return &MockService_NotifySubscribe_Call{Call: _e.mock.On("NotifySubscribe", ctx, acc, params)}
}

func (_c *MockService_NotifySubscribe_Call) Run(run func(ctx context.Context, acc *account.Account, params withings.NotifySubscribeParams)) *MockService_NotifySubscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *account.Account
		if args[1] != nil {
			arg1 = args[1].(*account.Account)
		}
		var arg2 withings.NotifySubscribeParams
		if args[2] != nil {
			arg2 = args[2].(withings.NotifySubscribeParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_NotifySubscribe_Call) Return(notifySubscribeResponse *withings.NotifySubscribeResponse, err error) *MockService_NotifySubscribe_Call {
	_c.Call.Return(notifySubscribeResponse, err)
	return _c
}

func (_c *MockService_NotifySubscribe_Call) RunAndReturn(run func(ctx context.Context, acc *account.Account, params withings.NotifySubscribeParams) (*withings.NotifySubscribeResponse, error)) *MockService_NotifySubscribe_Call {
	_c.Call.Return(run)
	return _c
}

// SleepGet provides a mock function for the type MockService
func (_mock *MockService) SleepGet(ctx context.Context, acc *account.Account, params withings.SleepGetParams) (*withings.SleepGetResponse, error) {
	ret := _mock.Called(ctx, acc, params)

	if len(ret) == 0 {
		panic("no return value specified for SleepGet")
	}

	var r0 *withings.SleepGetResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *account.Account, withings.SleepGetParams) (*withings.SleepGetResponse, error)); ok {
		return returnFunc(ctx, acc, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *account.Account, withings.SleepGetParams) *withings.SleepGetResponse); ok {
		r0 = returnFunc(ctx, acc, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*withings.SleepGetResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *account.Account, withings.SleepGetParams) error); ok {
		r1 = returnFunc(ctx, acc, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_SleepGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SleepGet'
type MockService_SleepGet_Call struct {
	*mock.Call
}

// SleepGet is a helper method to define mock.On call
//   - ctx context.Context
//   - acc *account.Account
//   - params withings.SleepGetParams
func (_e *MockService_Expecter) SleepGet(ctx interface{}, acc interface{}, params interface{}) *MockService_SleepGet_Call {
	return &MockService_SleepGet_Call{Call: _e.mock.On("SleepGet", ctx, acc, params)}
}

func (_c *MockService_SleepGet_Call) Run(run func(ctx context.Context, acc *account.Account, params withings.SleepGetParams)) *MockService_SleepGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *account.Account
		if args[1] != nil {
			arg1 = args[1].(*account.Account)
		}
		var arg2 withings.SleepGetParams
		if args[2] != nil {
			arg2 = args[2].(withings.SleepGetParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_SleepGet_Call) Return(sleepGetResponse *withings.SleepGetResponse, err error) *MockService_SleepGet_Call {
	_c.Call.Return(sleepGetResponse, err)
	return _c
}

func (_c *MockService_SleepGet_Call) RunAndReturn(run func(ctx context.Context, acc *account.Account, params withings.SleepGetParams) (*withings.SleepGetResponse, error)) *MockService_SleepGet_Call {
	_c.Call.Return(run)
	return _c
}

// SleepGetsummary provides a mock function for the type MockService
func (_mock *MockService) SleepGetsummary(ctx context.Context, acc *account.Account, params withings.SleepGetsummaryParams) (*withings.SleepGetsummaryResponse, error) {
	ret := _mock.Called(ctx, acc, params)

	if len(ret) == 0 {
		panic("no return value specified for SleepGetsummary")
	}

	var r0 *withings.SleepGetsummaryResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *account.Account, withings.SleepGetsummaryParams) (*withings.SleepGetsummaryResponse, error)); ok {
		return returnFunc(ctx, acc, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *account.Account, withings.SleepGetsummaryParams) *withings.SleepGetsummaryResponse); ok {
		r0 = returnFunc(ctx, acc, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*withings.SleepGetsummaryResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *account.Account, withings.SleepGetsummaryParams) error); ok {
		r1 = returnFunc(ctx, acc, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_SleepGetsummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SleepGetsummary'
type MockService_SleepGetsummary_Call struct {
	*mock.Call
}

// SleepGetsummary is a helper method to define mock.On call
//   - ctx context.Context
//   - acc *account.Account
//   - params withings.SleepGetsummaryParams
func (_e *MockService_Expecter) SleepGetsummary(ctx interface{}, acc interface{}, params interface{}) *MockService_SleepGetsummary_Call {
	return &MockService_SleepGetsummary_Call{Call: _e.mock.On("SleepGetsummary", ctx, acc, params)}
}

func (_c *MockService_SleepGetsummary_Call) Run(run func(ctx context.Context, acc *account.Account, params withings.SleepGetsummaryParams)) *MockService_SleepGetsummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *account.Account
		if args[1] != nil {
			arg1 = args[1].(*account.Account)
		}
		var arg2 withings.SleepGetsummaryParams
		if args[2] != nil {
			arg2 = args[2].(withings.SleepGetsummaryParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_SleepGetsummary_Call) Return(sleepGetsummaryResponse *withings.SleepGetsummaryResponse, err error) *MockService_SleepGetsummary_Call {
	_c.Call.Return(sleepGetsummaryResponse, err)
	return _c
}

func (_c *MockService_SleepGetsummary_Call) RunAndReturn(run func(ctx context.Context, acc *account.Account, params withings.SleepGetsummaryParams) (*withings.SleepGetsummaryResponse, error)) *MockService_SleepGetsummary_Call {
	_c.Call.Return(run)
	return _c
}
