package account

import (
	"context"
	"errors"
	"github.com/google/uuid"
)

var ErrAccountNotFound = errors.New("account not found")

// Mock generated by `make generate-mocks` (mockery v3, configured via
// .mockery.yaml at the repo root).
type Repo interface {
	GetAccountByWithingsUserID(ctx context.Context, withingsUserID string) (*Account, error)
	GetAccountByUUID(ctx context.Context, accountUUID uuid.UUID) (*Account, error)
	CreateAccount(ctx context.Context, account *Account) error
	ListAccounts(ctx context.Context) ([]*Account, error)
	Update(ctx context.Context, accountUUID uuid.UUID, updateFn func(ctx context.Context, acc *Account) (*Account, error)) error
}
