// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package account

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepo creates a new instance of MockRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepo {
	mock := &MockRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepo is an autogenerated mock type for the Repo type
type MockRepo struct {
	mock.Mock
}

type MockRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepo) EXPECT() *MockRepo_Expecter {
	return &MockRepo_Expecter{mock: &_m.Mock}
}

// CreateAccount provides a mock function for the type MockRepo
func (_mock *MockRepo) CreateAccount(ctx context.Context, account *Account) error {
	ret := _mock.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Account) error); ok {
		r0 = returnFunc(ctx, account)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepo_CreateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccount'
type MockRepo_CreateAccount_Call struct {
	*mock.Call
}

// CreateAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - account *Account
func (_e *MockRepo_Expecter) CreateAccount(ctx interface{}, account interface{}) *MockRepo_CreateAccount_Call {
	return &MockRepo_CreateAccount_Call{Call: _e.mock.On("CreateAccount", ctx, account)}
}

func (_c *MockRepo_CreateAccount_Call) Run(run func(ctx context.Context, account *Account)) *MockRepo_CreateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Account
		if args[1] != nil {
			arg1 = args[1].(*Account)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepo_CreateAccount_Call) Return(err error) *MockRepo_CreateAccount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepo_CreateAccount_Call) RunAndReturn(run func(ctx context.Context, account *Account) error) *MockRepo_CreateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccountByUUID provides a mock function for the type MockRepo
func (_mock *MockRepo) GetAccountByUUID(ctx context.Context, accountUUID uuid.UUID) (*Account, error) {
	ret := _mock.Called(ctx, accountUUID)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountByUUID")
	}

	var r0 *Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*Account, error)); ok {
		return returnFunc(ctx, accountUUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *Account); ok {
		r0 = returnFunc(ctx, accountUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, accountUUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepo_GetAccountByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountByUUID'
type MockRepo_GetAccountByUUID_Call struct {
	*mock.Call
}

// GetAccountByUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - accountUUID uuid.UUID
func (_e *MockRepo_Expecter) GetAccountByUUID(ctx interface{}, accountUUID interface{}) *MockRepo_GetAccountByUUID_Call {
	return &MockRepo_GetAccountByUUID_Call{Call: _e.mock.On("GetAccountByUUID", ctx, accountUUID)}
}

func (_c *MockRepo_GetAccountByUUID_Call) Run(run func(ctx context.Context, accountUUID uuid.UUID)) *MockRepo_GetAccountByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepo_GetAccountByUUID_Call) Return(account *Account, err error) *MockRepo_GetAccountByUUID_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *MockRepo_GetAccountByUUID_Call) RunAndReturn(run func(ctx context.Context, accountUUID uuid.UUID) (*Account, error)) *MockRepo_GetAccountByUUID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccountByWithingsUserID provides a mock function for the type MockRepo
func (_mock *MockRepo) GetAccountByWithingsUserID(ctx context.Context, withingsUserID string) (*Account, error) {
	ret := _mock.Called(ctx, withingsUserID)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountByWithingsUserID")
	}

	var r0 *Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*Account, error)); ok {
		return returnFunc(ctx, withingsUserID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *Account); ok {
		r0 = returnFunc(ctx, withingsUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, withingsUserID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepo_GetAccountByWithingsUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountByWithingsUserID'
type MockRepo_GetAccountByWithingsUserID_Call struct {
	*mock.Call
}

// GetAccountByWithingsUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - withingsUserID string
func (_e *MockRepo_Expecter) GetAccountByWithingsUserID(ctx interface{}, withingsUserID interface{}) *MockRepo_GetAccountByWithingsUserID_Call {
	return &MockRepo_GetAccountByWithingsUserID_Call{Call: _e.mock.On("GetAccountByWithingsUserID", ctx, withingsUserID)}
}

func (_c *MockRepo_GetAccountByWithingsUserID_Call) Run(run func(ctx context.Context, withingsUserID string)) *MockRepo_GetAccountByWithingsUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepo_GetAccountByWithingsUserID_Call) Return(account *Account, err error) *MockRepo_GetAccountByWithingsUserID_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *MockRepo_GetAccountByWithingsUserID_Call) RunAndReturn(run func(ctx context.Context, withingsUserID string) (*Account, error)) *MockRepo_GetAccountByWithingsUserID_Call {
	_c.Call.Return(run)
	return _c
}

// ListAccounts provides a mock function for the type MockRepo
func (_mock *MockRepo) ListAccounts(ctx context.Context) ([]*Account, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAccounts")
	}

	var r0 []*Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*Account, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*Account); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepo_ListAccounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAccounts'
type MockRepo_ListAccounts_Call struct {
	*mock.Call
}

// ListAccounts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepo_Expecter) ListAccounts(ctx interface{}) *MockRepo_ListAccounts_Call {
	return &MockRepo_ListAccounts_Call{Call: _e.mock.On("ListAccounts", ctx)}
}

func (_c *MockRepo_ListAccounts_Call) Run(run func(ctx context.Context)) *MockRepo_ListAccounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepo_ListAccounts_Call) Return(accounts []*Account, err error) *MockRepo_ListAccounts_Call {
	_c.Call.Return(accounts, err)
	return _c
}

func (_c *MockRepo_ListAccounts_Call) RunAndReturn(run func(ctx context.Context) ([]*Account, error)) *MockRepo_ListAccounts_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockRepo
func (_mock *MockRepo) Update(ctx context.Context, accountUUID uuid.UUID, updateFn func(ctx context.Context, acc *Account) (*Account, error)) error {
	ret := _mock.Called(ctx, accountUUID, updateFn)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, func(ctx context.Context, acc *Account) (*Account, error)) error); ok {
		r0 = returnFunc(ctx, accountUUID, updateFn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepo_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRepo_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - accountUUID uuid.UUID
//   - updateFn func(ctx context.Context, acc *Account) (*Account, error)
func (_e *MockRepo_Expecter) Update(ctx interface{}, accountUUID interface{}, updateFn interface{}) *MockRepo_Update_Call {
	return &MockRepo_Update_Call{Call: _e.mock.On("Update", ctx, accountUUID, updateFn)}
}

func (_c *MockRepo_Update_Call) Run(run func(ctx context.Context, accountUUID uuid.UUID, updateFn func(ctx context.Context, acc *Account) (*Account, error))) *MockRepo_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 func(ctx context.Context, acc *Account) (*Account, error)
		if args[2] != nil {
			arg2 = args[2].(func(ctx context.Context, acc *Account) (*Account, error))
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepo_Update_Call) Return(err error) *MockRepo_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepo_Update_Call) RunAndReturn(run func(ctx context.Context, accountUUID uuid.UUID, updateFn func(ctx context.Context, acc *Account) (*Account, error)) error) *MockRepo_Update_Call {
	_c.Call.Return(run)
	return _c
}
