// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package subscription

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepo creates a new instance of MockRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepo {
	mock := &MockRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepo is an autogenerated mock type for the Repo type
type MockRepo struct {
	mock.Mock
}

type MockRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepo) EXPECT() *MockRepo_Expecter {
	return &MockRepo_Expecter{mock: &_m.Mock}
}

// AllNotificationCategories provides a mock function for the type MockRepo
func (_mock *MockRepo) AllNotificationCategories(ctx context.Context) ([]NotificationCategory, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for AllNotificationCategories")
	}

	var r0 []NotificationCategory
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]NotificationCategory, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []NotificationCategory); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]NotificationCategory)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepo_AllNotificationCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllNotificationCategories'
type MockRepo_AllNotificationCategories_Call struct {
	*mock.Call
}

// AllNotificationCategories is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepo_Expecter) AllNotificationCategories(ctx interface{}) *MockRepo_AllNotificationCategories_Call {
	return &MockRepo_AllNotificationCategories_Call{Call: _e.mock.On("AllNotificationCategories", ctx)}
}

func (_c *MockRepo_AllNotificationCategories_Call) Run(run func(ctx context.Context)) *MockRepo_AllNotificationCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepo_AllNotificationCategories_Call) Return(notificationCategorys []NotificationCategory, err error) *MockRepo_AllNotificationCategories_Call {
	_c.Call.Return(notificationCategorys, err)
	return _c
}

func (_c *MockRepo_AllNotificationCategories_Call) RunAndReturn(run func(ctx context.Context) ([]NotificationCategory, error)) *MockRepo_AllNotificationCategories_Call {
	_c.Call.Return(run)
	return _c
}

// CreateNotification provides a mock function for the type MockRepo
func (_mock *MockRepo) CreateNotification(ctx context.Context, notification *Notification) error {
	ret := _mock.Called(ctx, notification)

	if len(ret) == 0 {
		panic("no return value specified for CreateNotification")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Notification) error); ok {
		r0 = returnFunc(ctx, notification)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepo_CreateNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNotification'
type MockRepo_CreateNotification_Call struct {
	*mock.Call
}

// CreateNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - notification *Notification
func (_e *MockRepo_Expecter) CreateNotification(ctx interface{}, notification interface{}) *MockRepo_CreateNotification_Call {
	return &MockRepo_CreateNotification_Call{Call: _e.mock.On("CreateNotification", ctx, notification)}
}

func (_c *MockRepo_CreateNotification_Call) Run(run func(ctx context.Context, notification *Notification)) *MockRepo_CreateNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Notification
		if args[1] != nil {
			arg1 = args[1].(*Notification)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepo_CreateNotification_Call) Return(err error) *MockRepo_CreateNotification_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepo_CreateNotification_Call) RunAndReturn(run func(ctx context.Context, notification *Notification) error) *MockRepo_CreateNotification_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRawNotification provides a mock function for the type MockRepo
func (_mock *MockRepo) CreateRawNotification(ctx context.Context, rawNotification *RawNotification) error {
	ret := _mock.Called(ctx, rawNotification)

	if len(ret) == 0 {
		panic("no return value specified for CreateRawNotification")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *RawNotification) error); ok {
		r0 = returnFunc(ctx, rawNotification)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepo_CreateRawNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRawNotification'
type MockRepo_CreateRawNotification_Call struct {
	*mock.Call
}

// CreateRawNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - rawNotification *RawNotification
func (_e *MockRepo_Expecter) CreateRawNotification(ctx interface{}, rawNotification interface{}) *MockRepo_CreateRawNotification_Call {
	return &MockRepo_CreateRawNotification_Call{Call: _e.mock.On("CreateRawNotification", ctx, rawNotification)}
}

func (_c *MockRepo_CreateRawNotification_Call) Run(run func(ctx context.Context, rawNotification *RawNotification)) *MockRepo_CreateRawNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *RawNotification
		if args[1] != nil {
			arg1 = args[1].(*RawNotification)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepo_CreateRawNotification_Call) Return(err error) *MockRepo_CreateRawNotification_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepo_CreateRawNotification_Call) RunAndReturn(run func(ctx context.Context, rawNotification *RawNotification) error) *MockRepo_CreateRawNotification_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSubscriptionIfNotExists provides a mock function for the type MockRepo
func (_mock *MockRepo) CreateSubscriptionIfNotExists(ctx context.Context, subscription *Subscription) error {
	ret := _mock.Called(ctx, subscription)

	if len(ret) == 0 {
		panic("no return value specified for CreateSubscriptionIfNotExists")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Subscription) error); ok {
		r0 = returnFunc(ctx, subscription)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepo_CreateSubscriptionIfNotExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSubscriptionIfNotExists'
type MockRepo_CreateSubscriptionIfNotExists_Call struct {
	*mock.Call
}

// CreateSubscriptionIfNotExists is a helper method to define mock.On call
//   - ctx context.Context
//   - subscription *Subscription
func (_e *MockRepo_Expecter) CreateSubscriptionIfNotExists(ctx interface{}, subscription interface{}) *MockRepo_CreateSubscriptionIfNotExists_Call {
	return &MockRepo_CreateSubscriptionIfNotExists_Call{Call: _e.mock.On("CreateSubscriptionIfNotExists", ctx, subscription)}
}

func (_c *MockRepo_CreateSubscriptionIfNotExists_Call) Run(run func(ctx context.Context, subscription *Subscription)) *MockRepo_CreateSubscriptionIfNotExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Subscription
		if args[1] != nil {
			arg1 = args[1].(*Subscription)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepo_CreateSubscriptionIfNotExists_Call) Return(err error) *MockRepo_CreateSubscriptionIfNotExists_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepo_CreateSubscriptionIfNotExists_Call) RunAndReturn(run func(ctx context.Context, subscription *Subscription) error) *MockRepo_CreateSubscriptionIfNotExists_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRawNotification provides a mock function for the type MockRepo
func (_mock *MockRepo) DeleteRawNotification(ctx context.Context, rawNotification *RawNotification) error {
	ret := _mock.Called(ctx, rawNotification)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRawNotification")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *RawNotification) error); ok {
		r0 = returnFunc(ctx, rawNotification)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepo_DeleteRawNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRawNotification'
type MockRepo_DeleteRawNotification_Call struct {
	*mock.Call
}

// DeleteRawNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - rawNotification *RawNotification
func (_e *MockRepo_Expecter) DeleteRawNotification(ctx interface{}, rawNotification interface{}) *MockRepo_DeleteRawNotification_Call {
	return &MockRepo_DeleteRawNotification_Call{Call: _e.mock.On("DeleteRawNotification", ctx, rawNotification)}
}

func (_c *MockRepo_DeleteRawNotification_Call) Run(run func(ctx context.Context, rawNotification *RawNotification)) *MockRepo_DeleteRawNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *RawNotification
		if args[1] != nil {
			arg1 = args[1].(*RawNotification)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepo_DeleteRawNotification_Call) Return(err error) *MockRepo_DeleteRawNotification_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepo_DeleteRawNotification_Call) RunAndReturn(run func(ctx context.Context, rawNotification *RawNotification) error) *MockRepo_DeleteRawNotification_Call {
	_c.Call.Return(run)
	return _c
}

// GetNotificationByUUID provides a mock function for the type MockRepo
func (_mock *MockRepo) GetNotificationByUUID(ctx context.Context, notificationUUID uuid.UUID) (*Notification, error) {
	ret := _mock.Called(ctx, notificationUUID)

	if len(ret) == 0 {
		panic("no return value specified for GetNotificationByUUID")
	}

	var r0 *Notification
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*Notification, error)); ok {
		return returnFunc(ctx, notificationUUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *Notification); ok {
		r0 = returnFunc(ctx, notificationUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Notification)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, notificationUUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepo_GetNotificationByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNotificationByUUID'
type MockRepo_GetNotificationByUUID_Call struct {
	*mock.Call
}

// GetNotificationByUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - notificationUUID uuid.UUID
func (_e *MockRepo_Expecter) GetNotificationByUUID(ctx interface{}, notificationUUID interface{}) *MockRepo_GetNotificationByUUID_Call {
	return &MockRepo_GetNotificationByUUID_Call{Call: _e.mock.On("GetNotificationByUUID", ctx, notificationUUID)}
}

func (_c *MockRepo_GetNotificationByUUID_Call) Run(run func(ctx context.Context, notificationUUID uuid.UUID)) *MockRepo_GetNotificationByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepo_GetNotificationByUUID_Call) Return(notification *Notification, err error) *MockRepo_GetNotificationByUUID_Call {
	_c.Call.Return(notification, err)
	return _c
}

func (_c *MockRepo_GetNotificationByUUID_Call) RunAndReturn(run func(ctx context.Context, notificationUUID uuid.UUID) (*Notification, error)) *MockRepo_GetNotificationByUUID_Call {
	_c.Call.Return(run)
	return _c
}

// GetNotificationDataByAccountUUIDAndService provides a mock function for the type MockRepo
func (_mock *MockRepo) GetNotificationDataByAccountUUIDAndService(ctx context.Context, accountUUID uuid.UUID, service NotificationDataService) ([]*NotificationData, error) {
	ret := _mock.Called(ctx, accountUUID, service)

	if len(ret) == 0 {
		panic("no return value specified for GetNotificationDataByAccountUUIDAndService")
	}

	var r0 []*NotificationData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, NotificationDataService) ([]*NotificationData, error)); ok {
		return returnFunc(ctx, accountUUID, service)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, NotificationDataService) []*NotificationData); ok {
		r0 = returnFunc(ctx, accountUUID, service)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*NotificationData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, NotificationDataService) error); ok {
		r1 = returnFunc(ctx, accountUUID, service)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepo_GetNotificationDataByAccountUUIDAndService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNotificationDataByAccountUUIDAndService'
type MockRepo_GetNotificationDataByAccountUUIDAndService_Call struct {
	*mock.Call
}

// GetNotificationDataByAccountUUIDAndService is a helper method to define mock.On call
//   - ctx context.Context
//   - accountUUID uuid.UUID
//   - service NotificationDataService
func (_e *MockRepo_Expecter) GetNotificationDataByAccountUUIDAndService(ctx interface{}, accountUUID interface{}, service interface{}) *MockRepo_GetNotificationDataByAccountUUIDAndService_Call {
	return &MockRepo_GetNotificationDataByAccountUUIDAndService_Call{Call: _e.mock.On("GetNotificationDataByAccountUUIDAndService", ctx, accountUUID, service)}
}

func (_c *MockRepo_GetNotificationDataByAccountUUIDAndService_Call) Run(run func(ctx context.Context, accountUUID uuid.UUID, service NotificationDataService)) *MockRepo_GetNotificationDataByAccountUUIDAndService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 NotificationDataService
		if args[2] != nil {
			arg2 = args[2].(NotificationDataService)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepo_GetNotificationDataByAccountUUIDAndService_Call) Return(notificationDatas []*NotificationData, err error) *MockRepo_GetNotificationDataByAccountUUIDAndService_Call {
	_c.Call.Return(notificationDatas, err)
	return _c
}

func (_c *MockRepo_GetNotificationDataByAccountUUIDAndService_Call) RunAndReturn(run func(ctx context.Context, accountUUID uuid.UUID, service NotificationDataService) ([]*NotificationData, error)) *MockRepo_GetNotificationDataByAccountUUIDAndService_Call {
	_c.Call.Return(run)
	return _c
}

// GetNotificationDataByNotificationUUID provides a mock function for the type MockRepo
func (_mock *MockRepo) GetNotificationDataByNotificationUUID(ctx context.Context, notificationUUID uuid.UUID) ([]*NotificationData, error) {
	ret := _mock.Called(ctx, notificationUUID)

	if len(ret) == 0 {
		panic("no return value specified for GetNotificationDataByNotificationUUID")
	}

	var r0 []*NotificationData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*NotificationData, error)); ok {
		return returnFunc(ctx, notificationUUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*NotificationData); ok {
		r0 = returnFunc(ctx, notificationUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*NotificationData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, notificationUUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepo_GetNotificationDataByNotificationUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNotificationDataByNotificationUUID'
type MockRepo_GetNotificationDataByNotificationUUID_Call struct {
	*mock.Call
}

// GetNotificationDataByNotificationUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - notificationUUID uuid.UUID
func (_e *MockRepo_Expecter) GetNotificationDataByNotificationUUID(ctx interface{}, notificationUUID interface{}) *MockRepo_GetNotificationDataByNotificationUUID_Call {
	return &MockRepo_GetNotificationDataByNotificationUUID_Call{Call: _e.mock.On("GetNotificationDataByNotificationUUID", ctx, notificationUUID)}
}

func (_c *MockRepo_GetNotificationDataByNotificationUUID_Call) Run(run func(ctx context.Context, notificationUUID uuid.UUID)) *MockRepo_GetNotificationDataByNotificationUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepo_GetNotificationDataByNotificationUUID_Call) Return(notificationDatas []*NotificationData, err error) *MockRepo_GetNotificationDataByNotificationUUID_Call {
	_c.Call.Return(notificationDatas, err)
	return _c
}

func (_c *MockRepo_GetNotificationDataByNotificationUUID_Call) RunAndReturn(run func(ctx context.Context, notificationUUID uuid.UUID) ([]*NotificationData, error)) *MockRepo_GetNotificationDataByNotificationUUID_Call {
	_c.Call.Return(run)
	return _c
}

// GetNotificationsByAccountUUID provides a mock function for the type MockRepo
func (_mock *MockRepo) GetNotificationsByAccountUUID(ctx context.Context, accountUUID uuid.UUID) ([]*Notification, error) {
	ret := _mock.Called(ctx, accountUUID)

	if len(ret) == 0 {
		panic("no return value specified for GetNotificationsByAccountUUID")
	}

	var r0 []*Notification
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*Notification, error)); ok {
		return returnFunc(ctx, accountUUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*Notification); ok {
		r0 = returnFunc(ctx, accountUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*Notification)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, accountUUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepo_GetNotificationsByAccountUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNotificationsByAccountUUID'
type MockRepo_GetNotificationsByAccountUUID_Call struct {
	*mock.Call
}

// GetNotificationsByAccountUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - accountUUID uuid.UUID
func (_e *MockRepo_Expecter) GetNotificationsByAccountUUID(ctx interface{}, accountUUID interface{}) *MockRepo_GetNotificationsByAccountUUID_Call {
	return &MockRepo_GetNotificationsByAccountUUID_Call{Call: _e.mock.On("GetNotificationsByAccountUUID", ctx, accountUUID)}
}

func (_c *MockRepo_GetNotificationsByAccountUUID_Call) Run(run func(ctx context.Context, accountUUID uuid.UUID)) *MockRepo_GetNotificationsByAccountUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepo_GetNotificationsByAccountUUID_Call) Return(notifications []*Notification, err error) *MockRepo_GetNotificationsByAccountUUID_Call {
	_c.Call.Return(notifications, err)
	return _c
}

func (_c *MockRepo_GetNotificationsByAccountUUID_Call) RunAndReturn(run func(ctx context.Context, accountUUID uuid.UUID) ([]*Notification, error)) *MockRepo_GetNotificationsByAccountUUID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPendingRawNotifications provides a mock function for the type MockRepo
func (_mock *MockRepo) GetPendingRawNotifications(ctx context.Context) ([]*RawNotification, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingRawNotifications")
	}

	var r0 []*RawNotification
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*RawNotification, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*RawNotification); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*RawNotification)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepo_GetPendingRawNotifications_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingRawNotifications'
type MockRepo_GetPendingRawNotifications_Call struct {
	*mock.Call
}

// GetPendingRawNotifications is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepo_Expecter) GetPendingRawNotifications(ctx interface{}) *MockRepo_GetPendingRawNotifications_Call {
	return &MockRepo_GetPendingRawNotifications_Call{Call: _e.mock.On("GetPendingRawNotifications", ctx)}
}

func (_c *MockRepo_GetPendingRawNotifications_Call) Run(run func(ctx context.Context)) *MockRepo_GetPendingRawNotifications_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepo_GetPendingRawNotifications_Call) Return(rawNotifications []*RawNotification, err error) *MockRepo_GetPendingRawNotifications_Call {
	_c.Call.Return(rawNotifications, err)
	return _c
}

func (_c *MockRepo_GetPendingRawNotifications_Call) RunAndReturn(run func(ctx context.Context) ([]*RawNotification, error)) *MockRepo_GetPendingRawNotifications_Call {
	_c.Call.Return(run)
	return _c
}

// GetPendingSubscriptions provides a mock function for the type MockRepo
func (_mock *MockRepo) GetPendingSubscriptions(ctx context.Context) ([]*Subscription, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingSubscriptions")
	}

	var r0 []*Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*Subscription, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*Subscription); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepo_GetPendingSubscriptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingSubscriptions'
type MockRepo_GetPendingSubscriptions_Call struct {
	*mock.Call
}

// GetPendingSubscriptions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepo_Expecter) GetPendingSubscriptions(ctx interface{}) *MockRepo_GetPendingSubscriptions_Call {
	return &MockRepo_GetPendingSubscriptions_Call{Call: _e.mock.On("GetPendingSubscriptions", ctx)}
}

func (_c *MockRepo_GetPendingSubscriptions_Call) Run(run func(ctx context.Context)) *MockRepo_GetPendingSubscriptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepo_GetPendingSubscriptions_Call) Return(subscriptions []*Subscription, err error) *MockRepo_GetPendingSubscriptions_Call {
	_c.Call.Return(subscriptions, err)
	return _c
}

func (_c *MockRepo_GetPendingSubscriptions_Call) RunAndReturn(run func(ctx context.Context) ([]*Subscription, error)) *MockRepo_GetPendingSubscriptions_Call {
	_c.Call.Return(run)
	return _c
}

// GetRawNotificationByUUID provides a mock function for the type MockRepo
func (_mock *MockRepo) GetRawNotificationByUUID(ctx context.Context, rawNotificationUUID uuid.UUID) (*RawNotification, error) {
	ret := _mock.Called(ctx, rawNotificationUUID)

	if len(ret) == 0 {
		panic("no return value specified for GetRawNotificationByUUID")
	}

	var r0 *RawNotification
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*RawNotification, error)); ok {
		return returnFunc(ctx, rawNotificationUUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *RawNotification); ok {
		r0 = returnFunc(ctx, rawNotificationUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*RawNotification)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, rawNotificationUUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepo_GetRawNotificationByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRawNotificationByUUID'
type MockRepo_GetRawNotificationByUUID_Call struct {
	*mock.Call
}

// GetRawNotificationByUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - rawNotificationUUID uuid.UUID
func (_e *MockRepo_Expecter) GetRawNotificationByUUID(ctx interface{}, rawNotificationUUID interface{}) *MockRepo_GetRawNotificationByUUID_Call {
	return &MockRepo_GetRawNotificationByUUID_Call{Call: _e.mock.On("GetRawNotificationByUUID", ctx, rawNotificationUUID)}
}

func (_c *MockRepo_GetRawNotificationByUUID_Call) Run(run func(ctx context.Context, rawNotificationUUID uuid.UUID)) *MockRepo_GetRawNotificationByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepo_GetRawNotificationByUUID_Call) Return(rawNotification *RawNotification, err error) *MockRepo_GetRawNotificationByUUID_Call {
	_c.Call.Return(rawNotification, err)
	return _c
}

func (_c *MockRepo_GetRawNotificationByUUID_Call) RunAndReturn(run func(ctx context.Context, rawNotificationUUID uuid.UUID) (*RawNotification, error)) *MockRepo_GetRawNotificationByUUID_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubscriptionByUUID provides a mock function for the type MockRepo
func (_mock *MockRepo) GetSubscriptionByUUID(ctx context.Context, subscriptionUUID uuid.UUID) (*Subscription, error) {
	ret := _mock.Called(ctx, subscriptionUUID)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscriptionByUUID")
	}

	var r0 *Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*Subscription, error)); ok {
		return returnFunc(ctx, subscriptionUUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *Subscription); ok {
		r0 = returnFunc(ctx, subscriptionUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, subscriptionUUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepo_GetSubscriptionByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubscriptionByUUID'
type MockRepo_GetSubscriptionByUUID_Call struct {
	*mock.Call
}

// GetSubscriptionByUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - subscriptionUUID uuid.UUID
func (_e *MockRepo_Expecter) GetSubscriptionByUUID(ctx interface{}, subscriptionUUID interface{}) *MockRepo_GetSubscriptionByUUID_Call {
	return &MockRepo_GetSubscriptionByUUID_Call{Call: _e.mock.On("GetSubscriptionByUUID", ctx, subscriptionUUID)}
}

func (_c *MockRepo_GetSubscriptionByUUID_Call) Run(run func(ctx context.Context, subscriptionUUID uuid.UUID)) *MockRepo_GetSubscriptionByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepo_GetSubscriptionByUUID_Call) Return(subscription *Subscription, err error) *MockRepo_GetSubscriptionByUUID_Call {
	_c.Call.Return(subscription, err)
	return _c
}

func (_c *MockRepo_GetSubscriptionByUUID_Call) RunAndReturn(run func(ctx context.Context, subscriptionUUID uuid.UUID) (*Subscription, error)) *MockRepo_GetSubscriptionByUUID_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubscriptionByWebhookSecret provides a mock function for the type MockRepo
func (_mock *MockRepo) GetSubscriptionByWebhookSecret(ctx context.Context, webhookSecret string) (*Subscription, error) {
	ret := _mock.Called(ctx, webhookSecret)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscriptionByWebhookSecret")
	}

	var r0 *Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*Subscription, error)); ok {
		return returnFunc(ctx, webhookSecret)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *Subscription); ok {
		r0 = returnFunc(ctx, webhookSecret)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, webhookSecret)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepo_GetSubscriptionByWebhookSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubscriptionByWebhookSecret'
type MockRepo_GetSubscriptionByWebhookSecret_Call struct {
	*mock.Call
}

// GetSubscriptionByWebhookSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - webhookSecret string
func (_e *MockRepo_Expecter) GetSubscriptionByWebhookSecret(ctx interface{}, webhookSecret interface{}) *MockRepo_GetSubscriptionByWebhookSecret_Call {
	return &MockRepo_GetSubscriptionByWebhookSecret_Call{Call: _e.mock.On("GetSubscriptionByWebhookSecret", ctx, webhookSecret)}
}

func (_c *MockRepo_GetSubscriptionByWebhookSecret_Call) Run(run func(ctx context.Context, webhookSecret string)) *MockRepo_GetSubscriptionByWebhookSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepo_GetSubscriptionByWebhookSecret_Call) Return(subscription *Subscription, err error) *MockRepo_GetSubscriptionByWebhookSecret_Call {
	_c.Call.Return(subscription, err)
	return _c
}

func (_c *MockRepo_GetSubscriptionByWebhookSecret_Call) RunAndReturn(run func(ctx context.Context, webhookSecret string) (*Subscription, error)) *MockRepo_GetSubscriptionByWebhookSecret_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubscriptionsByAccountUUID provides a mock function for the type MockRepo
func (_mock *MockRepo) GetSubscriptionsByAccountUUID(ctx context.Context, accountUUID uuid.UUID) ([]*Subscription, error) {
	ret := _mock.Called(ctx, accountUUID)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscriptionsByAccountUUID")
	}

	var r0 []*Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*Subscription, error)); ok {
		return returnFunc(ctx, accountUUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*Subscription); ok {
		r0 = returnFunc(ctx, accountUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, accountUUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepo_GetSubscriptionsByAccountUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubscriptionsByAccountUUID'
type MockRepo_GetSubscriptionsByAccountUUID_Call struct {
	*mock.Call
}

// GetSubscriptionsByAccountUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - accountUUID uuid.UUID
func (_e *MockRepo_Expecter) GetSubscriptionsByAccountUUID(ctx interface{}, accountUUID interface{}) *MockRepo_GetSubscriptionsByAccountUUID_Call {
	return &MockRepo_GetSubscriptionsByAccountUUID_Call{Call: _e.mock.On("GetSubscriptionsByAccountUUID", ctx, accountUUID)}
}

func (_c *MockRepo_GetSubscriptionsByAccountUUID_Call) Run(run func(ctx context.Context, accountUUID uuid.UUID)) *MockRepo_GetSubscriptionsByAccountUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepo_GetSubscriptionsByAccountUUID_Call) Return(subscriptions []*Subscription, err error) *MockRepo_GetSubscriptionsByAccountUUID_Call {
	_c.Call.Return(subscriptions, err)
	return _c
}

func (_c *MockRepo_GetSubscriptionsByAccountUUID_Call) RunAndReturn(run func(ctx context.Context, accountUUID uuid.UUID) ([]*Subscription, error)) *MockRepo_GetSubscriptionsByAccountUUID_Call {
	_c.Call.Return(run)
	return _c
}

// ListSubscriptions provides a mock function for the type MockRepo
func (_mock *MockRepo) ListSubscriptions(ctx context.Context) ([]*Subscription, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListSubscriptions")
	}

	var r0 []*Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*Subscription, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*Subscription); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepo_ListSubscriptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSubscriptions'
type MockRepo_ListSubscriptions_Call struct {
	*mock.Call
}

// ListSubscriptions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepo_Expecter) ListSubscriptions(ctx interface{}) *MockRepo_ListSubscriptions_Call {
	return &MockRepo_ListSubscriptions_Call{Call: _e.mock.On("ListSubscriptions", ctx)}
}

func (_c *MockRepo_ListSubscriptions_Call) Run(run func(ctx context.Context)) *MockRepo_ListSubscriptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepo_ListSubscriptions_Call) Return(subscriptions []*Subscription, err error) *MockRepo_ListSubscriptions_Call {
	_c.Call.Return(subscriptions, err)
	return _c
}

func (_c *MockRepo_ListSubscriptions_Call) RunAndReturn(run func(ctx context.Context) ([]*Subscription, error)) *MockRepo_ListSubscriptions_Call {
	_c.Call.Return(run)
	return _c
}

// StoreNotificationData provides a mock function for the type MockRepo
func (_mock *MockRepo) StoreNotificationData(ctx context.Context, notificationData *NotificationData) error {
	ret := _mock.Called(ctx, notificationData)

	if len(ret) == 0 {
		panic("no return value specified for StoreNotificationData")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *NotificationData) error); ok {
		r0 = returnFunc(ctx, notificationData)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepo_StoreNotificationData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreNotificationData'
type MockRepo_StoreNotificationData_Call struct {
	*mock.Call
}

// StoreNotificationData is a helper method to define mock.On call
//   - ctx context.Context
//   - notificationData *NotificationData
func (_e *MockRepo_Expecter) StoreNotificationData(ctx interface{}, notificationData interface{}) *MockRepo_StoreNotificationData_Call {
	return &MockRepo_StoreNotificationData_Call{Call: _e.mock.On("StoreNotificationData", ctx, notificationData)}
}

func (_c *MockRepo_StoreNotificationData_Call) Run(run func(ctx context.Context, notificationData *NotificationData)) *MockRepo_StoreNotificationData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *NotificationData
		if args[1] != nil {
			arg1 = args[1].(*NotificationData)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepo_StoreNotificationData_Call) Return(err error) *MockRepo_StoreNotificationData_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepo_StoreNotificationData_Call) RunAndReturn(run func(ctx context.Context, notificationData *NotificationData) error) *MockRepo_StoreNotificationData_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockRepo
func (_mock *MockRepo) Update(ctx context.Context, subscriptionUUID uuid.UUID, updateFn func(ctx context.Context, sub *Subscription) (*Subscription, error)) error {
	ret := _mock.Called(ctx, subscriptionUUID, updateFn)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, func(ctx context.Context, sub *Subscription) (*Subscription, error)) error); ok {
		r0 = returnFunc(ctx, subscriptionUUID, updateFn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepo_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRepo_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - subscriptionUUID uuid.UUID
//   - updateFn func(ctx context.Context, sub *Subscription) (*Subscription, error)
func (_e *MockRepo_Expecter) Update(ctx interface{}, subscriptionUUID interface{}, updateFn interface{}) *MockRepo_Update_Call {
	return &MockRepo_Update_Call{Call: _e.mock.On("Update", ctx, subscriptionUUID, updateFn)}
}

func (_c *MockRepo_Update_Call) Run(run func(ctx context.Context, subscriptionUUID uuid.UUID, updateFn func(ctx context.Context, sub *Subscription) (*Subscription, error))) *MockRepo_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 func(ctx context.Context, sub *Subscription) (*Subscription, error)
		if args[2] != nil {
			arg2 = args[2].(func(ctx context.Context, sub *Subscription) (*Subscription, error))
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepo_Update_Call) Return(err error) *MockRepo_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepo_Update_Call) RunAndReturn(run func(ctx context.Context, subscriptionUUID uuid.UUID, updateFn func(ctx context.Context, sub *Subscription) (*Subscription, error)) error) *MockRepo_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateNotification provides a mock function for the type MockRepo
func (_mock *MockRepo) UpdateNotification(ctx context.Context, notificationUUID uuid.UUID, updateFn func(ctx context.Context, notification *Notification) (*Notification, error)) error {
	ret := _mock.Called(ctx, notificationUUID, updateFn)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNotification")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, func(ctx context.Context, notification *Notification) (*Notification, error)) error); ok {
		r0 = returnFunc(ctx, notificationUUID, updateFn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepo_UpdateNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateNotification'
type MockRepo_UpdateNotification_Call struct {
	*mock.Call
}

// UpdateNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - notificationUUID uuid.UUID
//   - updateFn func(ctx context.Context, notification *Notification) (*Notification, error)
func (_e *MockRepo_Expecter) UpdateNotification(ctx interface{}, notificationUUID interface{}, updateFn interface{}) *MockRepo_UpdateNotification_Call {
	return &MockRepo_UpdateNotification_Call{Call: _e.mock.On("UpdateNotification", ctx, notificationUUID, updateFn)}
}

func (_c *MockRepo_UpdateNotification_Call) Run(run func(ctx context.Context, notificationUUID uuid.UUID, updateFn func(ctx context.Context, notification *Notification) (*Notification, error))) *MockRepo_UpdateNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 func(ctx context.Context, notification *Notification) (*Notification, error)
		if args[2] != nil {
			arg2 = args[2].(func(ctx context.Context, notification *Notification) (*Notification, error))
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepo_UpdateNotification_Call) Return(err error) *MockRepo_UpdateNotification_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepo_UpdateNotification_Call) RunAndReturn(run func(ctx context.Context, notificationUUID uuid.UUID, updateFn func(ctx context.Context, notification *Notification) (*Notification, error)) error) *MockRepo_UpdateNotification_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRawNotification provides a mock function for the type MockRepo
func (_mock *MockRepo) UpdateRawNotification(ctx context.Context, rawNotificationUUID uuid.UUID, updateFn func(ctx context.Context, rawNotification *RawNotification) (*RawNotification, error)) error {
	ret := _mock.Called(ctx, rawNotificationUUID, updateFn)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRawNotification")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, func(ctx context.Context, rawNotification *RawNotification) (*RawNotification, error)) error); ok {
		r0 = returnFunc(ctx, rawNotificationUUID, updateFn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepo_UpdateRawNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRawNotification'
type MockRepo_UpdateRawNotification_Call struct {
	*mock.Call
}

// UpdateRawNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - rawNotificationUUID uuid.UUID
//   - updateFn func(ctx context.Context, rawNotification *RawNotification) (*RawNotification, error)
func (_e *MockRepo_Expecter) UpdateRawNotification(ctx interface{}, rawNotificationUUID interface{}, updateFn interface{}) *MockRepo_UpdateRawNotification_Call {
	return &MockRepo_UpdateRawNotification_Call{Call: _e.mock.On("UpdateRawNotification", ctx, rawNotificationUUID, updateFn)}
}

func (_c *MockRepo_UpdateRawNotification_Call) Run(run func(ctx context.Context, rawNotificationUUID uuid.UUID, updateFn func(ctx context.Context, rawNotification *RawNotification) (*RawNotification, error))) *MockRepo_UpdateRawNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 func(ctx context.Context, rawNotification *RawNotification) (*RawNotification, error)
		if args[2] != nil {
			arg2 = args[2].(func(ctx context.Context, rawNotification *RawNotification) (*RawNotification, error))
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepo_UpdateRawNotification_Call) Return(err error) *MockRepo_UpdateRawNotification_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepo_UpdateRawNotification_Call) RunAndReturn(run func(ctx context.Context, rawNotificationUUID uuid.UUID, updateFn func(ctx context.Context, rawNotification *RawNotification) (*RawNotification, error)) error) *MockRepo_UpdateRawNotification_Call {
	_c.Call.Return(run)
	return _c
}
